### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/David_W#1]
I see a commit message 7ee0005393a234f7cfe75d8c74fe8942292e55f9 that requests assistance. Do you still need help and if so could you expand on the issue you are experiencing?

**Comment by daveydog24** [comment]
the commit message was actually for the swapi assignment but i accidently used the same message for a few of the assignments because my tree hadnt been sent for a while. thanks for checking and for everything
